CREATE TABLE TB_AUTHORITY(
	AUTHORITY_ID NUMBER AUTO_INCREMENT NOT NULL,
	USER_ID VARCHAR2(50) NOT NULL,
	AUTHORITY_TYPE VARCHAR2(8) NOT NULL,
	PRIMARY KEY(AUTHORITY_ID)
);

--회원 테이블 FK
ALTER TABLE TB_AUTHORITY ADD FOREIGN KEY(USER_ID) REFERENCES TB_USER(USER_ID);