CREATE TABLE TB_USER(
	USER_ID VARCHAR2(50) NOT NULL,
	USER_NAME VARCHAR2(200) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL,
	GENDER VARCHAR2(8) NOT NULL,
	BIRTH_DAY DATE NULL,
	REGISTRATION_DATE DATETIME NOT NULL,
	PRIMARY KEY(USER_ID)
);